//[Name, Position, Rating]
const playerData = [["Alexander","Wing",9]
    ,["Kahn","Center",9]
    ,["Thomas","Center",9]
    ,["Sanne","Center",9]
    ,["Ricky","Back",9]
    ,["Jef","Wing",8]
    ,["Roy","Back",8]
    ,["Wim S.","Wing",8]
    ,["Mirte","Wing",7]
    ,["Bas","_Front",7]
    ,["Wim D.C.","Wing",7]
    ,["Leszak","Back",6]
    ,["Elmer","_Front",6]
    ,["Florian","_Front",5]
    ,["Max","_Front",4]
    ,["Jolien","_Front",4]
    ,["Glen","_Front",4]
    ,["Sander","_Front",4]
    ,["Ezgi","Wing",3]
    ,["Wesley","_Front",3]
    ,["Maarten","_Front",3]
    ,["Kris","Back",3]
    ,["Jan","_Front",4]
    ,["Fran","_Front",3]
    ,["Clansy","Back",8]
    ,["Back 1","Back",1]
    ,["Front 1","_Front",1]]
