//[Name, Position, Rating]
const playerData = [
    ["Alexander Rechts", "Wing", 10],
    ["Alexander Links", "Wing", 8],
    ["Kahn", "Center", 10],
    ["Thomas", "Center", 9],
    ["Sanne", "Center", 9],
    ["Ricky", "Back", 9],
    ["Jef", "Back", 9],
    ["Roy", "Back", 8],
    ["Wim S.", "Wing", 9],
    ["Mirte", "Wing", 8],
    ["Bas", "_Front", 7],
    ["Wim D.C.", "Wing", 7],
    ["Leszak", "Back", 7],
    ["Elmer", "_Front", 6],
    ["Florian", "_Front", 5],
    ["Max", "Wing", 6],
    ["Jolien", "Wing", 5],
    ["Glen", "_Front", 6],
    ["Sander", "_Front", 6],
    ["Ezgi", "Wing", 5],
    ["Wesley", "_Front", 4],
    ["Maarten", "Wing", 6],
    ["Kris", "Back", 3],
    ["Jan", "_Front", 7],
    ["Fran", "_Front", 4],
    ["Clansy", "Back", 8],
    ["Back 1", "Back", 1],
    ["Front 1", "_Front", 1]
];
