//[Name, Position, Rating]
const playerData = [["Kahn", "center", 5],
                    ["Kris", "back", 1],
                    ["Sander", "_front", 2],
                    ["Sanne", "center", 5],
                    ["Glen", "_front", 2],
                    ["Wim D.C.", "wing", 3],
                    ["Jolien", "_front", 2],
                    ["Wesley", "wing", 1],
                    ["Jef", "wing", 4],
                    ["Alexander","wing",5],
                    ["Ricky","back",5],
                    ["Max", "_front",2],
                    ["Roy", "back", 5],
                    ["Thomas", "center", 5],
                    ["Bas", "_front", 4],
                    ["Elmer", "_front", 3],
                    ["Wim S.", "wing", 4],
                    ["Mirte", "wing", 4],
                    ["Florian", "wing", 2],
                    ["Ezgi", "_front", 2],
                    ["Maarten", "_front", 1],
                    ["Leszak", "back", 3]]
