// [name, function, history, imgsrc]
const bestuurData = [
    ["Zoë Broers", "Praeses", "Schacht, Schachtentemmer, Vice-Praeses", "media/bestuur22-23/zoe.jpg"],
    ["Sien Gaublomme", "Vice-Praeses", "Schacht, Penningmeester, Secretaris", "media/bestuur22-23/sien.jpg"],
    ["Hendrik Tillemans", "Secretaris & Cantor", "Schacht, Schachtentemmer, Doopmeester", "media/bestuur22-23/hendrik2.jpg"],
    ["Kayleigh Van Rompaey", "Secretaris", "Schacht", "media/schild.jpg"],
    ["Lisse Moreels", "Penningmeester", "Schacht", "media/bestuur22-23/lisse.jpg"],
    ["Renske Lodewijkx", "Doopmeester", "Schacht", "media/schild.jpg"],
    ["Jools Desmet", "Schachtentemmer", "Schacht, Feest", "media/bestuur22-23/jools.jpg"],
    ["Jille Schönberger", "Schachtentemmer", "Schacht", "media/schild.jpg"],
    ["Amber Gillard", "Schachtentemmer", "Schacht", "media/bestuur22-23/amber.jpg"],
    ["Noa De Pooter", "Schachtentemmer", "Schacht", "media/bestuur22-23/noa.jpg"],
    ["Jef Grupping", "Webmaster", "Schacht, Schachtentemmer, Webmaster, Webmaster & Weekend", "media/bestuur22-23/jef.jpg"],
    ["Eline Van de Veken", "Media", "Schacht, Schachtentemmer", "media/bestuur22-23/eline.jpg"],
    ["Vincent Michiels", "Media", "Schacht, Doopmeester, Penningmeester", "media/bestuur22-23/vincent.jpg"],
    ["Robbe Seghers", "Media", "Schacht, Media", "media/bestuur22-23/robbe.jpg"],
    ["Shaun Rosbach", "Media", "Schacht", "media/schild.jpg"],
    ["Maaren Wullus", "Feest", "Schacht, Medewerker", "media/schild.jpg"],
    ["Lars De Vos", "Feest & Sport ", "Schacht, Schachtentemmer", "media/bestuur22-23/lars.jpg"],
    ["Naomi Kahan", "Sport", "Schacht, Schachtentemmer", "media/bestuur22-23/naomi.jpg"],
    ["Kevin Nahoel", "Sport", "Schacht", "media/schild.jpg"],
    ["Robin Sonck", "Happy Team", "Schacht, Happy Team", "media/bestuur22-23/robin.jpg"],
    ["Marthe Horemans", "Happy Team", "Schacht", "media/schild.jpg"],
    ["Renée De Vries Neefs", "Weekend", "Schacht", "media/schild.jpg"],
    ["Louise Van de Looverbosch", "Kookmama", "Schacht, Penningmeester, Vice-Praeses, Praeses", "media/bestuur22-23/louise.jpg"]
]

const tijdlijnData = [
    "Leo Ven",
    "Leo Ven",
    "Wim Van Herck",
    "Inge Smedts",
    "Olga Coutrin",
    "Ralph De Wit",
    "Bart Delbaen",
    "Eric Lauwers",
    "Eric Lauwers",
    "Marc Demarche",
    "Marc Demarche",
    "Philippe Vis",
    "Serge Everdepoel",
    "Stijn Broucke",
    "Ronny Macharis",
    "Mark Beyst",
    "Bieke Verbeeck",
    "Tom Rommens",
    "Tom Rommens",
    "Sara Daman",
    "Karel De Wilde",
    "Nic Vanhorenbeeck",
    "Illya Swinnen",
    "Wim Dekkers",
    "Wim Dekkers",
    "Maarten Brusseleers",
    "Maarten Brusseleers",
    "Brecht Heremans",
    "Janna Vinck",
    "Hellen Van Der Veeken",
    "Wannes Dierckx",
    "Bart Van Cauwenbergh",
    "Rob Heyman",
    "Laura De Geyter",
    "Yannick De Schepper",
    "Birgit van Hoof",
    "Jana Schellemans",
    "Lizzy van Hoof",
    "Anouck Joos",
    "Alexandre Kahn",
    "Wim Huyghe",
    "Toon Willems",
    "Axelle Stoffels",
    "Achille Van Himbeeck",
    "Louise Van de Looverbosch",
    "Zoë Broers"
]

const slidesData = [
    ["media/img1.jpg", "Receptie 40 jaar Antverpia"],
    ["media/img2.jpg", "Saint-V 2019"],
    ["media/img3.jpg", "Bestuursweekend 2021"],
    ["media/img4.jpg", "Viva la Vida TD samen met KBS"],
    ["media/img5.jpg", "Antwerp 10 Miles"]
]